#Based on https://github.com/PaulGoldschmidt/OSAMD-Docs
#German configuration
site_name: Heidelberger E-Sport-Tage - Wissenshub
site_author: Paul Goldschmidt
site_url: https://wiki.esport-heidelberg.de/
repo_name: ESHD-Wiki
repo_url: https://github.com/esportheidelberg/ESHD-Docs
#repo_title: OSAMD-Docs
copyright: Copyright &copy; 2020-2023 E-Sport Heidelberg, Contributors
edit_uri: https://github.com/esportheidelberg/ESHD-Docs/edit/main/docs
theme:
  name: material
  #custom_dir: docs/assets/overrides
  language: de
  favicon: assets/images/ui/p3g3/favicons/favicon.ico
  logo: assets/images/ui/p3g3/logo/logo-normalized.png
  icon: 
    repo: fontawesome/brands/github
  features: 
    - navigation.top
    # - navigation.expand
    - navigation.instant
    - navigation.tabs
    # - toc.integrate
  palette:
    - scheme: esportheidelberg
      primary: cyan #mostly overriden in extra.css
      accent: orange
      toggle: 
        icon: material/weather-sunny
        name: Light Mode
    - scheme: default
      primary: grey
      accent: orange
      toggle: 
        icon: material/weather-night
        name: Dark Mode
plugins: 
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/esportheidelberg
      name: Github
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@esportheidelberg
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/esportheidelberg/
extra_css:
  - assets/stylesheets/global.css
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/js/newtab.js
nav:
  - Home: index.md
  - Anleitungen:
    - Organisation:
      - Allgemein:
        - Social Media: anleitungen/organisation/allgemein/social-media.md
        - Team-Mangement: anleitungen/organisation/allgemein/team-management.md
        - Zugangsdaten verwalten: anleitungen/organisation/allgemein/zugangsdaten-verwalten.md
        - Die Organisations-Rollen: anleitungen/organisation/allgemein/orga-rollen.md
      - Die Events:
        - Vor dem Event:
          - Ein Helfer-Team finden: anleitungen/organisation/zeitkritisch/vor-dem-event/team-finden.md
          - Werbung: anleitungen/organisation/zeitkritisch/vor-dem-event/werbung.md
          - Teilnehmerdaten richtig verwalten: anleitungen/organisation/zeitkritisch/vor-dem-event/teilnehmerdaten-verwalten.md
        - Während dem Event:
          - Presse beim Event: anleitungen/organisation/waehrend-dem-event/presse.md
        - Nach dem Event:
          - Nachbereitung: anleitungen/organisation/nach-dem-event/nachbereitung.md
          - Die nächste Generation "E-Sport Heidelberg" finden: anleitungen/organisation/nach-dem-event/die-naechste-generation.md
    - Technik:
      - Streamingsetup: anleitungen/technik/streamingsetup.md
      - YouTube-Setup: anleitungen/technik/youtubesetup.md
    - Eventtechnik:
      - Grundüberlegungen: anleitungen/eventtechnik/grundueberlegungen.md
      - Planung der Eventtechnik: anleitungen/eventtechnik/planung.md
    - Wiki:
      - Richtig Bearbeiten: anleitungen/wiki/richtig-bearbeiten.md
  - Übersichtsseiten:
    - Wissenswertes:
      - Warum sich engagieren?: uebersicht/wissenswertes/warum-engagieren.md
      - Personalaufwand bei den E-Sport-Tagen: uebersicht/wissenswertes/personalaufwand.md
      - Kosten der Heidelberger E-Sport-Tage: uebersicht/wissenswertes/kosten-esporttage.md
    - Orte:
      - Bürgerhaus Heidelberg: uebersicht/orte/heidelberg-buergerhaus.md
      - Halle 02: uebersicht/orte/heidelberg-halle02.md
      - Neckahalle Heidelberg: uebersicht/orte/heidelberg-neckarhalle.md
      - Stadtjugendring Heidelberg: uebersicht/orte/heidelberg-stadtjugendring.md
    - Spiele:
      - Counter-Strike Globale Offensive: uebersicht/spiele/csgo.md
      - FIFA: uebersicht/spiele/fifa.md
      - League of Legends: uebersicht/spiele/league-of-legends.md
      - Rocket League: uebersicht/spiele/rocketleague.md
      - Valorant: uebersicht/spiele/valorant.md
      - Regelwerke:
        - Counter-Strike Globale Offensive: uebersicht/spiele/regelwerke/regelwerk-csgo.md
        - FIFA: uebersicht/spiele/regelwerke/regelwerk-fifa.md
        - Rocket League: uebersicht/spiele/regelwerke/regelwerk-rocketleague.md
        - Valorant: uebersicht/spiele/regelwerke/regelwerk-valorant.md
    - Partner:
      - Jugendgemeinderat Heidelberg: uebersicht/partner/heidelberg-jugendgemeinderat.md
      - Stadtjugendring Heidelberg: uebersicht/partner/heidelberg-stadtjugendring.md
      - E-Sport Rhein-Neckar: uebersicht/partner/mannheim-esportrheinneckar.md
    - Personen:
      - Emil Staab: uebersicht/personen/emilstaab.md
      - Angelika Magin: uebersicht/personen/angelikamagin.md
      - Steffen Wörner: uebersicht/personen/steffenwoerner.md
      - Jonas Stratmann: uebersicht/personen/jonasstratmann.md
      - Katharina Spinner: uebersicht/personen/katharinaspinner.md
      - Paul Goldschmidt: uebersicht/personen/paulgoldschmidt.md
  - Events:
    - E-Sport Tage 2021: events/esporttage2021.md
    - E-Sport Tage 2022: events/esporttage2022.md